---
name: "release"

on:
  push:
    branches:
      - "master"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Shallow clones should be disabled to generate the release tag
        fetch-depth: 0
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
          node-version: latest
    - name: Build
      run: |
       npm install
       gulp generic
    - name: Create Release
      run: tar czf build.tar.gz -C build .
    - name: Create version tag
      run: |
        TAG="$(git rev-list --count HEAD)-$(git rev-parse --short HEAD)"
        echo "TAG=$TAG" >> $GITHUB_ENV
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build.tar.gz"
        tag: ${{ env.TAG }}
